#!/usr/bin/env python3
import json
import re
from collections import Counter

with open('/workspace/0a976afa-9d91-494d-85d2-5832b5541cb3/sessions/agent_0083bca8-f4c0-4f11-b7af-9ca7124132ea/data/1w5l8bw/flat.json') as f:
    comments = json.load(f)

real_comments = [c for c in comments if c.get('body') != '[deleted]']

# Build cluster assignments programmatically to avoid counting errors
cluster_assignments = []
# Using the verified manual mapping
mapping = {
    0: "Community & Moderation",
    1: "Meta/Zuck & Competitive Landscape",
    2: "Meta/Zuck & Competitive Landscape",
    3: "Benchmark Skepticism & Performance",
    4: "Benchmark Skepticism & Performance",
    5: "Release Timing & Open Weights",
    6: "Release Timing & Open Weights",
    7: "Benchmark Skepticism & Performance",
    8: "Benchmark Skepticism & Performance",
    9: "Benchmark Skepticism & Performance",
    10: "Benchmark Skepticism & Performance",
    11: "Benchmark Skepticism & Performance",
    12: "Benchmark Skepticism & Performance",
    13: "Meta/Zuck & Competitive Landscape",
    14: "Meta/Zuck & Competitive Landscape",
    15: "Meta/Zuck & Competitive Landscape",
    16: "Meta/Zuck & Competitive Landscape",
    17: "Meta/Zuck & Competitive Landscape",
    18: "Meta/Zuck & Competitive Landscape",
    19: "Meta/Zuck & Competitive Landscape",
    20: "Meta/Zuck & Competitive Landscape",
    21: "Meta/Zuck & Competitive Landscape",
    22: "Meta/Zuck & Competitive Landscape",
    23: "Meta/Zuck & Competitive Landscape",
    24: "Meta/Zuck & Competitive Landscape",
    25: "Meta/Zuck & Competitive Landscape",
    26: "Meta/Zuck & Competitive Landscape",
    27: "Meta/Zuck & Competitive Landscape",
    28: "Model Specs, Size & Hardware",
    29: "Meta/Zuck & Competitive Landscape",
    30: "Meta/Zuck & Competitive Landscape",
    31: "Meta/Zuck & Competitive Landscape",
    32: "Meta/Zuck & Competitive Landscape",
    33: "Meta/Zuck & Competitive Landscape",
    34: "Meta/Zuck & Competitive Landscape",
    35: "Meta/Zuck & Competitive Landscape",
    36: "Meta/Zuck & Competitive Landscape",
    37: "Meta/Zuck & Competitive Landscape",
    38: "Benchmark Skepticism & Performance",
    39: "Meta/Zuck & Competitive Landscape",
    40: "Meta/Zuck & Competitive Landscape",
    41: "Meta/Zuck & Competitive Landscape",
    42: "Meta/Zuck & Competitive Landscape",
    43: "Meta/Zuck & Competitive Landscape",
    44: "Benchmark Skepticism & Performance",
    45: "Benchmark Skepticism & Performance",
    46: "Benchmark Skepticism & Performance",
    47: "Benchmark Skepticism & Performance",
    48: "Benchmark Skepticism & Performance",
    49: "Model Specs, Size & Hardware",
    50: "Model Specs, Size & Hardware",
    51: "Model Specs, Size & Hardware",
    52: "Benchmark Skepticism & Performance",
    53: "Benchmark Skepticism & Performance",
    54: "Benchmark Skepticism & Performance",
    55: "Model Specs, Size & Hardware",
    56: "Model Specs, Size & Hardware",
    57: "Model Specs, Size & Hardware",
    58: "Model Specs, Size & Hardware",
    59: "Model Specs, Size & Hardware",
    60: "Release Timing & Open Weights",
    61: "Release Timing & Open Weights",
    62: "Release Timing & Open Weights",
    63: "Release Timing & Open Weights",
    64: "Release Timing & Open Weights",
    65: "Release Timing & Open Weights",
    66: "Release Timing & Open Weights",
    67: "Release Timing & Open Weights",
    68: "Release Timing & Open Weights",
    69: "Release Timing & Open Weights",
    70: "Muse/Glimmer Model Discussion",
    71: "Muse/Glimmer Model Discussion",
    72: "Muse/Glimmer Model Discussion",
    73: "Muse/Glimmer Model Discussion",
    74: "Muse/Glimmer Model Discussion",
    75: "Muse/Glimmer Model Discussion",
    76: "Muse/Glimmer Model Discussion",
    77: "Muse/Glimmer Model Discussion",
    78: "Muse/Glimmer Model Discussion",
    79: "Muse/Glimmer Model Discussion",
    80: "Muse/Glimmer Model Discussion",
    81: "Muse/Glimmer Model Discussion",
    82: "Muse/Glimmer Model Discussion",
    83: "Muse/Glimmer Model Discussion",
    84: "Muse/Glimmer Model Discussion",
    85: "Muse/Glimmer Model Discussion",
    86: "Muse/Glimmer Model Discussion",
    87: "Muse/Glimmer Model Discussion",
    88: "Muse/Glimmer Model Discussion",
    89: "Muse/Glimmer Model Discussion",
    90: "Muse/Glimmer Model Discussion",
    91: "Muse/Glimmer Model Discussion",
    92: "Muse/Glimmer Model Discussion",
    93: "Muse/Glimmer Model Discussion",
    94: "Muse/Glimmer Model Discussion",
    95: "Muse/Glimmer Model Discussion",
    96: "Muse/Glimmer Model Discussion",
    97: "Muse/Glimmer Model Discussion",
    98: "Muse/Glimmer Model Discussion",
    99: "Muse/Glimmer Model Discussion",
    100: "Muse/Glimmer Model Discussion",
    101: "Muse/Glimmer Model Discussion",
    102: "Benchmark Skepticism & Performance",
    103: "Meta/Zuck & Competitive Landscape",
    104: "Meta/Zuck & Competitive Landscape",
    105: "Meta/Zuck & Competitive Landscape",
    106: "Meta/Zuck & Competitive Landscape",
    107: "Meta/Zuck & Competitive Landscape",
    108: "Meta/Zuck & Competitive Landscape",
    109: "Meta/Zuck & Competitive Landscape",
    110: "Meta/Zuck & Competitive Landscape",
    111: "Meta/Zuck & Competitive Landscape",
    112: "Meta/Zuck & Competitive Landscape",
    113: "Meta/Zuck & Competitive Landscape",
    114: "Meta/Zuck & Competitive Landscape",
    115: "Release Timing & Open Weights",
    116: "Model Specs, Size & Hardware",
    117: "Model Specs, Size & Hardware",
    118: "Meta/Zuck & Competitive Landscape",
    119: "Meta/Zuck & Competitive Landscape",
    120: "Release Timing & Open Weights",
    121: "Release Timing & Open Weights",
    122: "Release Timing & Open Weights",
    123: "Release Timing & Open Weights",
    124: "Release Timing & Open Weights",
    125: "Release Timing & Open Weights",
    126: "Muse/Glimmer Model Discussion",
    127: "Muse/Glimmer Model Discussion",
    128: "Muse/Glimmer Model Discussion",
    129: "Muse/Glimmer Model Discussion",
    130: "Muse/Glimmer Model Discussion",
    131: "Release Timing & Open Weights",
    132: "Release Timing & Open Weights",
    133: "Release Timing & Open Weights",
    134: "Release Timing & Open Weights",
    135: "Release Timing & Open Weights",
    136: "Muse/Glimmer Model Discussion",
    137: "Muse/Glimmer Model Discussion",
    138: "Model Specs, Size & Hardware",
    139: "Model Specs, Size & Hardware",
    140: "Model Specs, Size & Hardware",
    141: "Model Specs, Size & Hardware",
    142: "Model Specs, Size & Hardware",
    143: "Model Specs, Size & Hardware",
    144: "Model Specs, Size & Hardware",
    145: "Model Specs, Size & Hardware",
    146: "Model Specs, Size & Hardware",
    147: "Muse/Glimmer Model Discussion",
    148: "Meta/Zuck & Competitive Landscape",
    149: "Meta/Zuck & Competitive Landscape",
    150: "Meta/Zuck & Competitive Landscape",
    151: "Model Specs, Size & Hardware",
    152: "Muse/Glimmer Model Discussion",
    153: "Release Timing & Open Weights",
    154: "Release Timing & Open Weights",
    155: "Release Timing & Open Weights",
    156: "Meta/Zuck & Competitive Landscape",
    157: "Community & Moderation",
    158: "Muse/Glimmer Model Discussion",
    159: "Muse/Glimmer Model Discussion",
    160: "Muse/Glimmer Model Discussion",
    161: "Muse/Glimmer Model Discussion",
    162: "Muse/Glimmer Model Discussion",
    163: "Muse/Glimmer Model Discussion",
    164: "Muse/Glimmer Model Discussion",
    165: "Muse/Glimmer Model Discussion",
    166: "Muse/Glimmer Model Discussion",
    167: "Model Specs, Size & Hardware",
    168: "Benchmark Skepticism & Performance",
    169: "Model Specs, Size & Hardware",
    170: "Model Specs, Size & Hardware",
    171: "Model Specs, Size & Hardware",
    172: "Model Specs, Size & Hardware",
    173: "Benchmark Skepticism & Performance",
    174: "Model Specs, Size & Hardware",
    175: "Model Specs, Size & Hardware",
    176: "Meta/Zuck & Competitive Landscape",
    177: "Model Specs, Size & Hardware",
    178: "Release Timing & Open Weights",
    179: "Muse/Glimmer Model Discussion",
    180: "Model Specs, Size & Hardware",
    181: "Benchmark Skepticism & Performance",
    182: "Benchmark Skepticism & Performance",
    183: "Model Specs, Size & Hardware",
    184: "Meta/Zuck & Competitive Landscape",
    185: "Meta/Zuck & Competitive Landscape",
    186: "Release Timing & Open Weights",
    187: "Benchmark Skepticism & Performance",
    188: "Benchmark Skepticism & Performance",
    189: "Community & Moderation",
    190: "Release Timing & Open Weights",
    191: "Community & Moderation",
    192: "Community & Moderation",
}

for i in range(193):
    cluster_assignments.append(mapping[i])

print(f"Total assignments: {len(cluster_assignments)}")
counts = Counter(cluster_assignments)
for k, v in counts.most_common():
    print(f"  {k}: {v}")
print(f"Sum: {sum(counts.values())}")